load("//tools:defaults.bzl", "ng_module")

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "clover",
    package_name = "@nguniversal/common/clover",
    srcs = glob([
        "src/**/*.ts",
        "*.ts",
    ]),
    deps = [
        "@npm//@angular/common",
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
        "@npm//rxjs",
    ],
)
